// Generated by Dagger (https://dagger.dev).
package com.example.homefinancialassistant.viewmodels.modules;

import com.example.homefinancialassistant.di.modules.MathModule;
import com.example.homefinancialassistant.domain.Interactor;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
public final class MathModule_ProvideInteractorFactory implements Factory<Interactor> {
  private final MathModule module;

  public MathModule_ProvideInteractorFactory(MathModule module) {
    this.module = module;
  }

  @Override
  public Interactor get() {
    return provideInteractor(module);
  }

  public static MathModule_ProvideInteractorFactory create(MathModule module) {
    return new MathModule_ProvideInteractorFactory(module);
  }

  public static Interactor provideInteractor(MathModule instance) {
    return Preconditions.checkNotNullFromProvides(instance.provideInteractor());
  }
}
