// Generated by Dagger (https://dagger.dev).
package com.example.homefinancialassistant.viewmodels.modules;

import com.example.homefinancialassistant.di.modules.MathModule;
import com.example.homefinancialassistant.utils.Credit;
import dagger.internal.DaggerGenerated;
import dagger.internal.Factory;
import dagger.internal.Preconditions;
import dagger.internal.QualifierMetadata;
import dagger.internal.ScopeMetadata;

@ScopeMetadata
@QualifierMetadata
@DaggerGenerated
public final class MathModule_ProvideCreditFactory implements Factory<Credit> {
  private final MathModule module;

  public MathModule_ProvideCreditFactory(MathModule module) {
    this.module = module;
  }

  @Override
  public Credit get() {
    return provideCredit(module);
  }

  public static MathModule_ProvideCreditFactory create(MathModule module) {
    return new MathModule_ProvideCreditFactory(module);
  }

  public static Credit provideCredit(MathModule instance) {
    return Preconditions.checkNotNullFromProvides(instance.provideCredit());
  }
}
